'use strict';

module.exports = function(request) {
    if (request == 'philosophy') {
        return {
            "browser": "../../browser.json",
            "name": "Progressive Insights - Philosophy",
            "mainTitle": "Our Philosophy",
            "contents": [{
                "type": "para",
                "text": "Progressive Insights is a social movement to humanize data for the benefit of society. We belive that the data generted by a society can be used to solve the problems facing the same society. "
            }, {
                "type": "para",
                "text": "However, Data in itself are not sufficient, as they are inanimate and passive. We at progressive insights are passionate about giving life to inanimate data and turing them into impactful results. We use data driven intelligence as a potent tool to solve social and economic probelms facing india.  "
            }, {
                "type": "para",
                "text": "At progressive insights we firmly belive in democratizing data driven intelligence. We identify and key decision makers in social and public sector organiations and empower them with impactful insights, thus turning inanimate data into actionable insights. We also partner with the social and public sector organziations to measure the continous progress of the social impact. "
            }, {
                "type": "img-para",
                "imgData": {
                    "imgPosition": "left",
                    "textPosition": "right",
                    "src":"",
                    "text": "Our vision is to empower social and public sector instititions with data driven intelligence and actionable insights to solve social and economic problems of the society. ​"
                }
            }, {
                "type": "para",
                "text": "At progressive inisghts the primary mission of our dedicated group of volunteers is to actiavte data science initiatives in social and public sector institutions and measure impact and their continuous progress."
            }, {
                "type": "img-para",
                "imgData": {
                    "imgPosition": "right",
                    "textPosition": "left",
                    "src": "",
                    "text": "At progressive insights we are driven by the following set of values:"
                }
            }, {
                "type": "bulleted-list",
                "items": ["Selfless service to others", "Professionalism", "Ethical Integrity"]
            },  {
                "type": "para",
                "text": "At Progressive Insights, live the concept of servant leadership and believe in giving back to society through knowledge based philanthropy."
            }]
        };
    }
    if (request == 'organization') {
        return {
            "browser": "../../browser.json",
            "name": "Progressive Insights - Organization",
            "mainTitle": "Organization",
            "contents": [{
                "type": "large-heading",
                "text": "Who We Are"
            }, {
                "type": "para",
                "text": "Progressive Insights is an International Non-Profit organization founded in January 2016, head quartered in Boston, USA."
            }, {
                "type": "img-para",
                "imgData": {
                  "imgPosition": "left",
                  "textPosition": "right",
                  "text": "At Progressive insights we believe that the problems created by the society can be solved with the data generated by the same society. Data we believe contains in it hidden stories of economic inequality, educational discrepancies, environmental problems and many other untold stories of human suffering. ",
                  "src": ""
                }
            },
            {
              "type": "para",
              "text": "We are the world’s first organization serving the society through its four pillars: Data Science, Data Literacy, Data Advocacy, and Data Research. Founded in January 2016 by two analytics professionals with a common goal and passion to serve the society, Progressive Insights is a Public Charitable Trust located in the United States and India."
            },
            {
                "type": "large-heading",
                "text": "Serving Society"
            }, {
                "type": "para",
                "text": "We empower nonprofit organizations, governments, think tanks, international organizations with data driven approaches and factual insights. We serve social sector institutions through our four pillars: Data Research, Data Literacy, Data Science and Data Advocacy."
            }, {
                "type": "large-heading",
                "text": "Who We Serve"
            }, {
                "type": "para",
                "text": "We empower nonprofit organizations, governments, think tanks, international " +
                    "organizations with data driven approaches and factual insights. We serve social sector " +
                    "institutions through our four pillars: Data Research, Data Literacy, Data Science and Data Advocacy."
            }, {
                "type": "img",
                "src": "../lib/images/cycle.jpg"
            }, {
                "type": "large-heading",
                "text": "Our Focus Areas"
            }, {
                "type": "bold-para",
                "text": {
                    "boldText": "Rural Development",
                    "regularText": "Agricultural development, Water management, rural good governance"
                }
            }, {
                "type": "bold-para",
                "text": {
                    "boldText": "Education",
                    "regularText": "Improve Quality of education, Education Inequality"
                }
            }, {
                "type": "bold-para",
                "text": {
                    "boldText": "Poverty",
                    "regularText": "Food security, Economic inequality"
                }
            }, {
                "type": "bold-para",
                "text": {
                    "boldText": "Environment",
                    "regularText": "Environmental health, Pollution"
                }
            }, {
                "type": "bold-para",
                "text": {
                    "boldText": "Public Health",
                    "regularText": "Health Disparities, Over Population, HIV/AIDS"
                }
            }]
        };
    }
    if (request == 'social-impact-lab') {
        return {
            "browser": "../../browser.json",
            "name": "Progressive Insights",
            "mainTitle": "Social Impact Lab",
            "contents": [{
                "type": "para",
                "text": "Every action that we undertake at Progressive Insights impacts the lives around us. The question we ask ourselves at our social impact lab is – How do we create a social impact in the world around us using systems thinking and data science?"
            }, {
                "type": "img",
                "src": "../lib/images/social.jpg"
            }]
        }
    }
    if (request == 'leadership') {
        return {
            "browser": "../../browser.json",
            "name": "Progressive Insights - Leadership",
            "mainTitle": "Our Leadership Team",
            "leaders": [{
                "imgSrc": "../lib/images/leaders/bharath.jpg",
                "title": "Bharath Shivaram - Chief Data Officer",
                "statement": "Tell people more about this item. Give people the info they " +
                    "need to go ahead and take the action you want. To make this item your own, click here.",
                "contact": "bharath@progressiveinsights.org"
            }, {
                "imgSrc": "../lib/images/leaders/parth.jpg",
                "title": "Parth Kulkarni - Chief Operating Officer",
                "statement": "Tell people more about this item. Give people the info they " +
                    "need to go ahead and take the action you want. To make this item your own, click here.",
                "contact": "parth@progressiveinsights.org"
            }, {
                "imgSrc": "../lib/images/leaders/mohan.jpg",
                "title": "Balamurugan Mohan - Data Sciences Leader",
                "statement": "Tell people more about this item. Give people the info they " +
                    "need to go ahead and take the action you want. To make this item your own, click here.",
                "contact": "bala@progressiveinsights.org"
            }, {
                "imgSrc": "../lib/images/leaders/dilip.jpg",
                "title": "Dilip Sagar Naidu - Data Sciences Leader",
                "statement": "Tell people more about this item. Give people the info they " +
                    "need to go ahead and take the action you want. To make this item your own, click here.",
                "contact": "dilip@progressiveinsights.org"
            }]
        };
    }
    if (request == 'donations') {
        return {

            "browser": "../../browser.json",
            "name": "Progressive Insights - Donate",
            "mainTitle": "Donations",
            "contents": [{
                "type": "large-heading",
                "text": "Make a Donation"
            }, {
                "type": "para",
                "text": "We, at Progressive Insights, are passionate about reaching our " +
                    "vision of empowering social sector institutions in order to improve the quality of life in our society."
            }, {
                "type": "paypal-button",
                "text": "Donate"
            }]
        };
    }
    if (request == 'contact') {
        return {
            "browser": "../../browser.json",
            "name": "Progressive Insights - Contact Us",
            "mainTitle": "Contact Us",
            "contents": [{
                "type": "form",
                "fields": [{
                        "messageSent": false,
                    },

                    {
                        "fieldType": "input",
                        "text": "Name",
                        "fieldLength": "regular",
                        "inputType": "text"
                    }, {
                        "fieldType": "input",
                        "text": "Email",
                        "fieldLength": "regular",
                        "inputType": "email"
                    }, {
                        "fieldType": "input",
                        "text": "Subject",
                        "fieldLength": "regular",
                        "inputType": "text"
                    }, {
                        "fieldType": "input",
                        "text": "Message",
                        "fieldLength": "large",
                        "inputType": "text"
                    }, {
                        "fieldType": "button",
                        "text": "Send"
                    }
                ]
            }, {
                "type": "contact-method",
                "methods": [{
                    "title": "Our Addresss",
                    "text": ["500 Terry Francois Street", "San Francisco, CA 94158", "info@mysite.com"]
                }, {
                    "title": "Call Us",
                    "text": ["Free Call: 1-800-000-0000", "Tel: 123-456-7890", "Fax: 123-456-7890"]
                }]
            }]
        };
    }
};
