'use strict';

module.exports = function(request) {
  if(request == 'philosophy') {
    return {
      "browser": "../../browser.json",
      "name": "Progressive Insights - Philosophy",
      "mainTitle": "Our Philosophy",
      "contents": [
        {
          "type": "para",
        "text":"At Progressive Insights, the primary goal of our dedicated"+
       "group of volunteers is to empower social sector institutions (non-profit"+
       "institutions serving the public good) make better decisions via a more data-driven"+
       " and systems-thinking approach."
     },
       {
         "type":"para",
         "text":"At Progressive Insights, our volunteers are driven by the following set of values:"
       },
       {
         "type": "bulleted-list",
         "items": ["Selfless service to others", "Professionalism", "Ethical Integrity"]
       },
       {
         "type": "para",
         "text": "At Progressive Insights, we believe that a group of thoughtful, committed citizens can change the world."
       },
       {
         "type": "para",
         "text":"We are committed about reaching our vision of empowering social sector"+
         " institutions to use data driven approaches and factual insights. Our mission is "+
         "to enable data science initiatives in social sector institutions and measure their continuous progress."
       }
     ]
   };
 }
 if(request == 'organization') {
   return {
     "browser": "../../browser.json",
     "name": "Progressive Insights - Organization",
     "mainTitle": "Organization",
     "contents": [
       {
       "type": "large-heading",
       "text": "Who We Are"
     },
     {
       "type": "para",
       "text": "Progressive Insights is an International Non-Profit organization founded in January 2016, head quartered in Boston, USA."
     },
     {
       "type": "para",
       "text": "We are the world’s first organization serving the society through its "+
       "four pillars: Data Science, Data Literacy, Data Advocacy, and Data Research. Founded in "+
       "January 2016 by two analytics professionals with a common goal and passion to serve the society, "+
       "Progressive Insights is a 501(c)(3) registered nonprofit organization located here in the United States and India."
     },
     {
       "type": "large-heading",
       "text": "Why We Exist"
     },
     {
       "type": "para",
       "text": "At Progressive insights we believe that the problems created by the society can "+
       "be solved with the data generated by the same society. Data we believe contains in it hidden "+
       "stories of economic inequality, educational discrepancies, environmental problems and many other untold stories of human suffering. "
     },
     {
       "type": "large-heading",
       "text": "Who We Serve"
     },
     {
       "type": "para",
       "text": "We empower nonprofit organizations, governments, think tanks, international "+
       "organizations with data driven approaches and factual insights. We serve social sector "+
       "institutions through our four pillars: Data Research, Data Literacy, Data Science and Data Advocacy."
     },
     {
       "type": "img",
       "src": "../lib/images/cycle.jpg"
     },
     {
       "type": "large-heading",
       "text": "Our Focus Areas"
     },
     {
       "type": "bold-para",
       "text": {
         "boldText": "Rural Development",
         "regularText": "Agricultural development, Water management, rural good governance"
       }
     },
     {
       "type": "bold-para",
       "text": {
         "boldText": "Education",
         "regularText": "Improve Quality of education, Education Inequality"
       }
     },
     {
       "type": "bold-para",
       "text": {
         "boldText": "Poverty",
         "regularText": "Food security, Economic inequality"
       }
     },
     {
       "type": "bold-para",
       "text": {
         "boldText": "Environment",
         "regularText": "Environmental health, Pollution"
       }
     },
     {
       "type": "bold-para",
       "text": {
         "boldText": "Public Health",
         "regularText": "Health Disparities, Over Population, HIV/AIDS"
       }
     }
   ]
   };
 }
 if(request == 'social-impact-lab') {
   return {
     "browser": "../../browser.json",
     "name": "Progressive Insights",
     "mainTitle": "Social Impact Lab",
     "contents": [
       {
         "type": "para",
         "text": "Every action that we undertake at progressive insights impacts the "+
         "lives around us. The question we ask at social impact do is – How do we create social "+
         "impact in the world around using systems thinking and data science."
       },
       {
         "type": "img",
         "src": "../lib/images/social.jpg"
       }
     ]
   }
 }
 if(request=='leadership') {
   return {
     "browser": "../../browser.json",
     "name": "Progressive Insights - Leadership",
     "mainTitle": "Our Leadership Team",
     "leaders": [
       {
         "imgSrc": "../lib/images/leaders/bharath.jpg",
         "title": "Bharath Shivaram - Chief Data Officer",
         "statement": "Tell people more about this item. Give people the info they "+
         "need to go ahead and take the action you want. To make this item your own, click here.",
         "contact": "bharath@progressiveinsights.org"
       },
       {
         "imgSrc": "../lib/images/leaders/parth.jpg",
         "title": "Parth Kulkarni - Chief Operating Officer",
         "statement": "Tell people more about this item. Give people the info they "+
         "need to go ahead and take the action you want. To make this item your own, click here.",
         "contact": "parth@progressiveinsights.org"
       },
       {
         "imgSrc": "../lib/images/leaders/mohan.jpg",
         "title": "Balamurugan Mohan - Data Sciences Leader",
         "statement": "Tell people more about this item. Give people the info they "+
         "need to go ahead and take the action you want. To make this item your own, click here.",
         "contact": "bala@progressiveinsights.org"
       },
       {
         "imgSrc": "../lib/images/leaders/dilip.jpg",
         "title": "Dilip Sagar Naidu - Data Sciences Leader",
         "statement": "Tell people more about this item. Give people the info they "+
         "need to go ahead and take the action you want. To make this item your own, click here.",
         "contact": "dilip@progressiveinsights.org"
       }
     ]
   };
 }
 if(request == 'donations') {
   return  {

   "browser": "../../browser.json",
   "name": "Progressive Insights - Donate",
   "mainTitle": "Donations",
   "contents": [
     {
       "type": "large-heading",
       "text": "Make a Donation"
     },
     {
       "type": "para",
       "text": "We, at Progressive Insights, are passionate about reaching our "+
       "vision of empowering social sector institutions in order to improve the quality of life in our society."
     },
     {
       "type": "paypal-button",
       "text": "Donate"
     }
   ]
 };
 }
 if(request == 'contact') {
   return {
     "browser": "../../browser.json",
   "name": "Progressive Insights - Contact Us",
   "mainTitle": "Contact Us",
   "contents": [
     {
       "type": "form",
       "fields": [
         {
           "fieldType": "input",
           "text": "Name",
           "fieldLength": "regular",
           "inputType": "text"
         },
         {
           "fieldType": "input",
           "text": "Email",
           "fieldLength": "regular",
           "inputType": "email"
         },
         {
           "fieldType": "input",
           "text": "Subject",
           "fieldLength": "regular",
           "inputType": "text"
         },
         {
           "fieldType": "input",
           "text": "Message",
           "fieldLength": "large",
           "inputType": "text"
         },
         {
           "type": "button",
           "text": "Send"
         }
       ]
     },
     {
       "type": "contact-method",
       "methods": [
         {
           "title": "Our Addresss",
           "text" : ["500 Terry Francois Street", "San Francisco, CA 94158", "info@mysite.com"]
         },
         {
           "title": "Call Us",
           "text": ["Free Call: 1-800-000-0000", "Tel: 123-456-7890", "Fax: 123-456-7890"]
         }
       ]
     }
   ]
 };
 }
};
